changelog:
  exclude:
    labels:
      - ignore-changelog
    authors:
      - dependabot
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
        - feature
        - feat
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "🧰 Maintenance & Refactoring"
      labels:
        - chore
        - documentation
        - refactor
