changelog:
  title: "What's Changed"
  exclude:
    labels:
      - ignore-changelog
      - internal
    authors:
      - dependabot
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
        - feature
        - feat
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "⚡ Performance"
      labels:
        - performance
    - title: "📖 Documentation"
      labels:
        - documentation
    - title: "🧰 Maintenance"
      labels:
        - chore
        - refactor
