name: CI Pipeline

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cod
        uses: actions/checkout@v4

      # 1. Construim imaginea folosind Dockerfile-ul pe care l-am reparat împreună
      - name: Build Docker Image
        run: docker build -t cluster .

      # 2. Rulăm suita de teste DIRECT în interiorul imaginii Docker
      - name: Run Tests inside Docker Container
        run: docker run --rm cluster pytest --cov=app

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cod
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install & Verificari
        run: |
          cd frontend
          npm ci
          npm run lint
          npm run typecheck
          npm run test
          npm run build
